import 'package:flutter/material.dart';
import 'package:project_counselling/app/views/AppWidgets/AppText.dart';
import 'package:project_counselling/app/views/AppWidgets/CustomAppBar.dart';
import 'package:project_counselling/app/views/AppWidgets/DefaultBackground.dart';
import 'package:project_counselling/app/views/Utils/Dimensions.dart';

class TermsAndServiceScreen extends StatelessWidget {
  const TermsAndServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;
    return Scaffold(
      body: Defaultbackground(
        child: SafeArea(
          child: Column(
            children: [
              CustomAppbar(title: "Terms of Service"),
              Expanded(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 24,
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      AppText(text: 'Last updated: Nov 3, 2024'),
                      SizedBox(height: Dimensions.height(16)),

                      // Introduction
                      _buildSectionTitle('1. Acceptance of Terms', textTheme),
                      _buildSectionContent(
                        'By creating an account and using this application, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, you may not use our services.',
                        textTheme,
                      ),

                      // Scope of Service
                      _buildSectionTitle('2. Scope and Limitation of Service', textTheme),
                      _buildSectionContent(
                        'This application provides AI-driven conversations for emotional exploration and wellness tools like breathing exercises. It is not a licensed medical, therapeutic, or crisis support service. The responses generated by the AI are for informational and supportive purposes only and are not a substitute for professional medical advice, diagnosis, or treatment from a qualified healthcare provider.',
                        textTheme,
                      ),
                      _buildSubSectionTitle('Emergency Disclaimer', textTheme),
                      _buildSectionContent(
                        'If you are experiencing a mental health crisis, or if you are in immediate danger, please contact emergency services (e.g., 911) or a crisis hotline immediately. This app is not monitored and cannot provide emergency support.',
                        textTheme,
                      ),

                      // User Accounts
                      _buildSectionTitle('3. User Accounts', textTheme),
                      _buildSectionContent(
                        'To use our services, you must create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to provide accurate and complete information when signing up.',
                        textTheme,
                      ),

                      // User Conduct
                      _buildSectionTitle('4. User Conduct', textTheme),
                      _buildSectionContent(
                        'You agree not to use the service to transmit any content that is unlawful, harmful, or otherwise objectionable. You are solely responsible for your interactions and the content you provide. Misuse of the service may result in the termination of your account.',
                        textTheme,
                      ),

                      // Service Usage and Limitations
                      _buildSectionTitle('5. Service Usage and Limitations', textTheme),
                      _buildSectionContent(
                        'Basic accounts are permitted to save a maximum of five (5) chat sessions. To save additional sessions beyond this limit, you must first delete an existing saved session.',
                        textTheme,
                      ),

                      // Third-Party Services
                      _buildSectionTitle('6. Third-Party Services', textTheme),
                      _buildSectionContent(
                        'Our service utilizes third-party providers, including Google\'s Firebase for data storage and authentication, and Google\'s Generative AI for chat functionalities. Your use of our app is also subject to the terms and policies of these third parties.',
                        textTheme,
                      ),

                      // Disclaimers and Limitation of Liability
                      _buildSectionTitle('7. Disclaimers and Limitation of Liability', textTheme),
                      _buildSectionContent(
                        'The service is provided "as is" without any warranties. We do not guarantee the accuracy, reliability, or suitability of the AI-generated responses. We are not liable for any damages or losses arising from your use of or inability to use the service.',
                        textTheme,
                      ),

                      // Changes to Terms
                      _buildSectionTitle('8. Changes to These Terms', textTheme),
                      _buildSectionContent(
                        'We reserve the right to modify these terms at any time. We will notify you of changes by updating the "Last updated" date. Your continued use of the app after such changes constitutes your acceptance of the new terms.',
                        textTheme,
                      ),

                      // Contact Us
                      _buildSectionTitle('9. Contact Us', textTheme),
                      _buildSectionContent(
                        'If you have any questions about these Terms of Service, please contact us at: shahjinay02@gmail.com',
                        textTheme,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title, TextTheme textTheme) {
    return Padding(
      padding: const EdgeInsets.only(top: 16.0, bottom: 8.0),
      child: AppText(
        text: title,
        style: textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold, fontSize: 18),
      ),
    );
  }

  Widget _buildSubSectionTitle(String title, TextTheme textTheme) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0, bottom: 4.0),
      child: AppText(
        text: title,
        style: textTheme.bodyLarge?.copyWith(fontWeight: FontWeight.w600, fontSize: 16),
      ),
    );
  }

  Widget _buildSectionContent(String content, TextTheme textTheme) {
    return AppText(
      text: content,
      style: textTheme.bodyMedium?.copyWith(height: 1.5, fontSize: 14),
    );
  }
}
